[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.5.0"
spin = "0.10.0"
x86_64 = "0.15.2"

[[bin]]
name = "kernel"
path = "src/main.rs"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
